version: '3'

services:
  build:
    image: maven:3.3-jdk-8
    volumes:
     - .:/project
     - ./repo:/root/.m2/repository
    working_dir: /project
    command: mvn clean verify

  reports:
    image: maven:3.3-jdk-8
    volumes:
     - .:/project
     - ./repo:/root/.m2/repository
    working_dir: /project
    command: mvn site

  server:
    image: maven:3.3-jdk-8
    volumes:
     - .:/project
     - ./repo:/root/.m2/repository
    working_dir: /project
    ports:
     - 8080:8080
    command: java -jar target/quality-1.0-SNAPSHOT.jar

  runtime-image:
    build:
      context: .
    image: qualimente/java-service-exercise
    ports:
     - 8080:8080
